### PR TITLE
Added Network Dashboard, Customized Auto Simulation, Logging and improvised CSS 

### PR DESCRIPTION
**Pull request by aachintya**
## Description

1. **Added NetworkDashboard.js**: Visualizes four key network metrics using Chart.js for clearer, more interactive insights.
2. **Improved CSS**: Made the site more dynamic and enhanced button styling for a smoother user experience. (since the issue was about better visualisation)
3. **Added Reset Button**: Allows users to reset the simulation without restarting the site.
4. **Real-Time Graph Updates**: Ensured live updates to the graphs for accurate tracking.
5. **Bug Fixes**: Resolved issues from previous versions to improve stability.
6.  **Auto-Simulation** - Added feature of auto simulation with custom packet loss percentage
7.  **Debug Info** - Added a debug info at the bottom of page to detect any anomalies
8.  **Report Feature** -  Added a Generate Report button which generates a pdf containing all graph visualisations for a particular simulation.
9. **Exporting the Data** - We can export the simulation data in the format as described in issue 2 in CSV or JSON format.

**Bugs** - One of the major bug was that the packet loss button was useless and the packet loss calculation was not being updated correctly when packets were marked as lost.

## Related Issue

Fixes # (issue)

[#3 ](https://github.com/ContriHUB/Congestion-Control-Simulator/issues/3)- Added logging for Simulator
[#2](https://github.com/ContriHUB/Congestion-Control-Simulator/issues/2) - Improved Visualisation of Traffic
[#1  ](https://github.com/ContriHUB/Congestion-Control-Simulator/issues/1)- Enable Users to Define Initial Network Conditions (Including Packet Loss) 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Motivation and Context

This change adds an auto simulator to the current manual simulator which indeeds makes the learning process better. Addition of charts helps in better visualisation and exporting data can help us gain insights about concepts of networking in detail.

## How Has This Been Tested?

Mostly its tested using css selector and console on the google chrome browser. Also i added some debug info in the code for better testing.

## Screenshots (if appropriate):
Screenshot 2024-10-16 at 12 20 51 PM
Screenshot 2024-10-16 at 12 21 21 PM
Screenshot 2024-10-16 at 12 21 47 PM
Screenshot 2024-10-16 at 12 23 09 PM

Sample Report - [simulation_report (5).pdf](https://github.com/user-attachments/files/17390679/simulation_report.5.pdf)
Sample CSV logs  - [simulation_logs (8).csv](https://github.com/user-attachments/files/17390685/simulation_logs.8.csv)
Sample JSON logs - [simulation_logs (2).json](https://github.com/user-attachments/files/17390686/simulation_logs.2.json)

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by aachintya** [comment]
Update - The black graph are now transparent and are more appealing to the eyes.

**Comment by Nandika-A** [comment]
Can you attach the screenshot with transparent graphs?

> Update - The black graph are now transparent and are more appealing to the eyes.

**Comment by aachintya** [comment]
> Can you attach the screenshot with transparent graphs?
> 
> > Update - The black graph are now transparent and are more appealing to the eyes.


Like these
Screenshot 2024-10-16 at 5 30 53 PM

[sample_report.pdf](https://github.com/user-attachments/files/17395269/sample_report.pdf)

**Review by Nandika-A — APPROVED** [review]
lgtm

**Comment by Nandika-A** [comment]
> lgtm

Request the issues on contrihub's site.

**Comment by aachintya** [comment]
> > lgtm
> 
> Request the issues on contrihub's site.

requested.

**Pull request merged**
